-- === Albums & Photos ===
create table if not exists albums (
  id              bigserial primary key,
  slug            varchar(120) not null unique,
  title           varchar(200) not null,
  description     CLOB,
  cover_image_url varchar(500),
  is_published    boolean not null default false,
  created_at      timestamp not null default now(),
  updated_at      timestamp not null default now()
);
create index if not exists idx_albums_created_at on albums(created_at desc);

create table if not exists photos (
  id              bigserial primary key,
  album_id        bigint not null,
  title           varchar(200),
  description     CLOB,
  image_url       varchar(500) not null,
  sort_order      int not null default 0,
  taken_at        timestamp,
  created_at      timestamp not null default now(),
  updated_at      timestamp not null default now(),
  constraint fk_photos_album foreign key (album_id) references albums(id) on delete cascade
);

create index if not exists idx_photos_album_order on photos(album_id, sort_order);

-- Events
CREATE TABLE if not exists events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug                VARCHAR(120)  NOT NULL UNIQUE,
  title               VARCHAR(200)  NOT NULL,
  summary             VARCHAR(500),
  description         text,
  location            VARCHAR(200),
  cover_image_url     VARCHAR(500),
  rsvp_url            VARCHAR(500),
  gallery_album_id    BIGINT,
  start_at            TIMESTAMP     NOT NULL,
  end_at              TIMESTAMP,
  is_published        BOOLEAN       NOT NULL DEFAULT FALSE,
  created_at          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  updated_at          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

-- 2) (Optional but recommended) Add a foreign key constraint
ALTER TABLE events
  ADD CONSTRAINT fk_events_gallery_album
  FOREIGN KEY (gallery_album_id) REFERENCES albums(id);

create index if not exists idx_events_start_at on events(start_at);
create index if not exists idx_events_published on events(is_published);

-- === Adverts ===
create table if not exists adverts (
  id              bigserial primary key,
  title           varchar(200) not null,
  image_url       varchar(500),
  target_url      varchar(500),
  placement       varchar(50) not null, -- e.g. HEADER, SIDEBAR, FOOTER
  starts_at       timestamp,
  ends_at         timestamp,
  is_active       boolean not null default false,
  created_at      timestamp not null default now(),
  updated_at      timestamp not null default now()
);
create index if not exists idx_adverts_active_time on adverts(is_active, starts_at, ends_at);

-- Suggestions (Postbox)
create table if not exists suggestions (
  id             bigserial primary key,
  name           varchar(200),
  email          varchar(320),
  message        CLOB,
  status         varchar(20) not null default 'NEW', -- NEW | REVIEWED | ARCHIVED
  internal_notes CLOB,
  created_at     TIMESTAMP not null default now()
);

create index if not exists idx_suggestions_status on suggestions(status);

-- People (Executives)
create table if not exists people (
  id           bigserial primary key,
  name         varchar(200) not null,
  role_title   varchar(200) not null,
  photo_url    text,
  bio          text,
  email        varchar(320),
  order_index  int not null default 0
);

create index if not exists idx_people_order on people(order_index);

-- === Pages ===
create table if not exists pages (
  id              bigserial primary key,
  slug            varchar(120) not null unique,
  title           varchar(200) not null,
  content         CLOB not null,
  is_published    boolean not null default false,
  updated_at      timestamp not null default now(),
  created_at      timestamp not null default now()
);




-- === Membership form submissions ===
create table if not exists membership_applications (
  id              bigserial primary key,
  full_name       varchar(200) not null,
  email           varchar(320) not null,
  phone           varchar(50),
  address         varchar(400),
  occupation      varchar(200),
  message         CLOB,
  created_at      timestamp not null default now()
);
create index if not exists idx_membership_created on membership_applications(created_at);

-- === Admin Users (stub) ===
create table if not exists users (
  id          bigserial primary key,
  username    varchar(100) not null unique,
  password    varchar(200) not null,
  role        varchar(50) not null default 'ADMIN', -- simple single-role model for now
  enabled     boolean not null default true,
  created_at  timestamp not null default now()
);