-- Albums first (referenced by Events and Photos)
create table if not exists albums (
  id               bigserial primary key,
  name             varchar(200) not null,
  description      text,
  cover_image_url  text,
  created_at       TIMESTAMP not null default now()
);

create index if not exists idx_albums_created_at on albums(created_at desc);

-- Photos
create table if not exists photos (
  id           bigserial primary key,
  album_id     bigint not null references albums(id) on delete cascade,
  image_url    text not null,
  caption      text,
  taken_at     TIMESTAMP,
  uploaded_at  TIMESTAMP not null default now()
);

create index if not exists idx_photos_album_id on photos(album_id);

-- Events
CREATE TABLE if not exists events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug                VARCHAR(120)  NOT NULL UNIQUE,
  title               VARCHAR(200)  NOT NULL,
  summary             VARCHAR(500),
  description         text,
  location            VARCHAR(200),
  cover_image_url     VARCHAR(500),
  rsvp_url            VARCHAR(500),
  gallery_album_id    BIGINT,
  start_at            TIMESTAMP     NOT NULL,
  end_at              TIMESTAMP,
  is_published        BOOLEAN       NOT NULL DEFAULT FALSE,
  created_at          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  updated_at          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

-- 2) (Optional but recommended) Add a foreign key constraint
ALTER TABLE events
  ADD CONSTRAINT fk_events_gallery_album
  FOREIGN KEY (gallery_album_id) REFERENCES albums(id);

create index if not exists idx_events_start_at on events(start_at);
create index if not exists idx_events_published on events(is_published);

-- Adverts
create table if not exists adverts (
  id               bigserial primary key,
  title            varchar(200) not null,
  image_url        text not null,
  body             text,
  link_url         text,
  contact_email    varchar(320),
  starts_on        date,
  ends_on          date,
  is_published     boolean not null default false,
  created_at       TIMESTAMP not null default now(),
  updated_at       TIMESTAMP not null default now()
);

create index if not exists idx_adverts_active on adverts(is_published, starts_on, ends_on);

-- Suggestions (Postbox)
create table if not exists suggestions (
  id             bigserial primary key,
  name           varchar(200),
  email          varchar(320),
  message        CLOB,
  status         varchar(20) not null default 'NEW', -- NEW | REVIEWED | ARCHIVED
  internal_notes CLOB,
  created_at     TIMESTAMP not null default now()
);

create index if not exists idx_suggestions_status on suggestions(status);

-- People (Executives)
create table if not exists people (
  id           bigserial primary key,
  name         varchar(200) not null,
  role_title   varchar(200) not null,
  photo_url    text,
  bio          text,
  email        varchar(320),
  order_index  int not null default 0
);

create index if not exists idx_people_order on people(order_index);

-- Pages (structured content as JSON text for flexibility)
create table if not exists pages (
  id          bigserial primary key,
  page_key    varchar(50) not null unique, -- 'home','about','guidelines','constitution','contactWidget'
  content_json text,
  updated_at  TIMESTAMP not null default now()
);
