-- Members
CREATE TABLE IF NOT EXISTS members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name    VARCHAR(120),
  last_name     VARCHAR(120),
  date_of_birth DATE,
  personal_nr   VARCHAR(64),
  address       VARCHAR(256),
  post_code     VARCHAR(32),
  city          VARCHAR(120),
  phone         VARCHAR(64),
  email         VARCHAR(320),
  occupation    VARCHAR(160),
  created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_members_email ON members(email);

-- Membership form settings
CREATE TABLE IF NOT EXISTS membership_form_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  url         VARCHAR(2048) NOT NULL,
  title       VARCHAR(255),
  description TEXT,
  updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
