-- Opprett tabellen som JPA forventer
CREATE TABLE IF NOT EXISTS album_items (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  album_id     BIGINT NOT NULL,
  title        VARCHAR(255),
  url          VARCHAR(2048),
  file_name    VARCHAR(512),
  thumb_url    VARCHAR(2048),
  content_type VARCHAR(255),
  size_bytes   BIGINT,
  kind         VARCHAR(16),
  created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  media_type   VARCHAR(16) NOT NULL
);

DO $$
BEGIN
  ALTER TABLE public.album_items
    ADD CONSTRAINT fk_album_items_album
    FOREIGN KEY (album_id) REFERENCES public.albums(id) ON DELETE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN
    -- FK already exists; nothing to do
    NULL;
END $$;


CREATE INDEX IF NOT EXISTS ix_album_items_album_id ON album_items(album_id);

-- Legg til publiseringskolonne på albums (H2/PG: BOOLEAN)
ALTER TABLE albums
  ADD COLUMN IF NOT EXISTS published BOOLEAN NOT NULL DEFAULT FALSE;
